# Generated by Django 4.2 on 2023-04-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_conversation_pdf_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
    ]
