# Generated by Django 4.2 on 2023-04-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_conversation_title_pdfdocument_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="vector_db_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
