# Generated by Django 4.2 on 2023-04-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_pdfdocument_vector_db_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdfdocument",
            name="vector_db_id",
        ),
    ]
