# Generated by Django 4.2 on 2023-04-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_remove_pdfdocument_vector_db_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfdocument",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
