# Generated by Django 4.2 on 2023-05-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_vectorstore_namespace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorstore",
            name="index",
            field=models.UUIDField(default="test", editable=False, unique=True),
        ),
    ]
