# Generated by Django 4.2 on 2023-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_alter_vectorstore_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorstore",
            name="index",
            field=models.CharField(default="test", editable=False, unique=True),
        ),
    ]
