# Generated by Django 4.2 on 2023-05-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0014_alter_vectorstore_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="conversation_type",
            field=models.CharField(
                choices=[("chat", "Chat"), ("pdf", "PDF"), ("yt-chat", "YT-chat")],
                default="chat",
                max_length=50,
            ),
        ),
    ]
