# Generated by Django 4.2 on 2023-05-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0016_youtubelink_conversation_yt_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectorstore",
            name="youtube_link",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.youtubelink",
            ),
        ),
    ]
