# Generated by Django 4.2 on 2023-05-28 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0018_knowledgebase"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("youtube_url", "YouTube URL"),
                            ("csv", "CSV"),
                            ("text", "Text"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("data", models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="conversation_type",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="pdf_document",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="yt_link",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="document_data",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="knowledgebase",
            name="vectorstore",
        ),
        migrations.RemoveField(
            model_name="vectorstore",
            name="document",
        ),
        migrations.RemoveField(
            model_name="vectorstore",
            name="youtube_link",
        ),
        migrations.AddField(
            model_name="conversation",
            name="knowledge_base",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.knowledgebase",
            ),
        ),
        migrations.AddField(
            model_name="vectorstore",
            name="knowledgebase",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.knowledgebase",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="documents",
            field=models.ManyToManyField(to="authentication.document"),
        ),
    ]
