# Generated by Django 4.2 on 2023-05-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0020_rename_document_knowledgedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectorstore",
            name="document",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.knowledgedocument",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="knowledgebase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="authentication.knowledgebase",
            ),
        ),
    ]
