# Generated by Django 4.2 on 2023-06-05 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0021_vectorstore_document_alter_vectorstore_knowledgebase"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="KnowledgeBaseSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("namespace", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                (
                    "knowledgebase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.knowledgebase",
                    ),
                ),
            ],
        ),
    ]
