# Generated by Django 4.2 on 2023-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0023_chunk"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgebasesummary",
            name="namespace",
        ),
        migrations.RemoveField(
            model_name="vectorstore",
            name="namespace",
        ),
        migrations.AddField(
            model_name="knowledgebase",
            name="namespace",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
