# Generated by Django 4.2 on 2023-06-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0024_remove_knowledgebasesummary_namespace_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chunk",
            old_name="text",
            new_name="content",
        ),
        migrations.AddField(
            model_name="chunk",
            name="metadata",
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
