# Generated by Django 4.2 on 2023-07-18 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0028_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.conversation",
            ),
        ),
    ]
