# Generated by Django 4.2 on 2023-07-19 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0029_knowledgedocument_conversation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgedocument",
            name="conversation",
        ),
    ]
